apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bmi-calculator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: bmi-calculator
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Dcse.service.registry.address=http://10.229.45.152:30100
        - name: JAR_NAME
          value: calculator-0.4.0-SNAPSHOT
        image: 10.229.40.121:8082/servicecomb/bmi:latest
        name: bmi-calculator